# Welcome to Jekyll!
# #
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lodi Row x Row Festival | May 15 & 16, 2020 at Lodi Lake
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Formally known as ZinFest, the Lodi Row x Row Festival returns to Lodi Lake for an iconic weekend of world-class wines and the friendly faces behind the craft.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://zinfest.com" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "https://lodirowxrow.com" 
url: "https://lodirowxrow.com" 

# baseurl: "" 
# url: "" 

kramdown:  
  parse_block_html: true

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

tickets:
  url: https://www.eventbrite.com/e/lodi-row-x-row-festival-2020-tickets-97829822633
  title: Buy Tickets
footer:
  present:
    title: "Event Presented By:"
    link:
      title: Visit Lodi Wine California's Website
      url: https://www.lodiwine.com/
      target: "_blank"
social:
  -
    title: facebook 
    url: https://www.facebook.com/LodiWine/
  -
    title: twitter 
    url: https://twitter.com/lodi_wine
  -
    title: instagram 
    url: https://www.instagram.com/lodi_wine/